name: Delete Main Branch
on: [push]
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Main
        run: git push origin --delete main || git push origin --delete master
